apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  selector:
    matchLabels:
      app: model-service
  replicas: 1
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
        - name: model-service
          image: aaradhyaghota/model-service:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
    ports:
      - port: 5000
        targetPort: 5000
    selector:
      app: model-service